version: '3.8'

services:
  app:
    image: zhak01/devops-fastapi-app:latest
    container_name: monitoring-dashboard
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis

    env_file:
      - .env

    environment:
      - REDIS_HOST=redis
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

  redis:
    image: redis:alpine
    container_name: my-redis-db
    restart: always